### ISSUE TITLE
Mild syntax-highlighting issues in blog

### ISSUE THREAD

**Issue by nbarnwell** [EventStore/geteventstore.com#54]
I'm reading up on Greg's re-hosted blog posts on projections and have noticed several code examples where the formatting is off. I'm not sure what, but it's probably a simple markdown issue or somesuch. I imagine it's somehow related to the content being migrated from Greg's own blog to the geteventstore.com blog.

Most pages of that blog series have at least one instance of this issue. Here's an example from https://geteventstore.com/blog/20130217/projections-intermission/:

![region](https://cloud.githubusercontent.com/assets/842125/17290442/5cb50032-57d6-11e6-82f5-961563727ae9.png)

**Comment by nbarnwell** [comment]
Sorry to say, but I don't think this is fixed at all? I've hard-refreshed my browser and still see the problem. Perhaps this was confused with another issue that was resolved?

**Comment by pgermishuys** [comment]
Looking into this now @nbarnwell, give me 5 minutes.

**Comment by pgermishuys** [comment]
This should be correct now @nbarnwell

**Comment by danleech** [comment]
@nbarnwell @pgermishuys Sorry guys, I’ve spent the afternoon fixing a bunch of typos and formatting issues in blog posts. I’m uploading the changes to our web server now.

For future reference, our website is not hosted on GitHub. Changes to this repo are not automatically reflected on the live website. Hope that clarifies things!

**Comment by danleech** [comment]
@nbarnwell You can see the changes on the live site now. Please do let me know if you spot any other formatting issues in our posts; I’m sure there are a few I missed.
